first_simple_form_variant:
    path: /contact
    controller: App\Controller\Message\ContactPageController::messageForm
    methods:    [GET]

write_to_db_at_first_simple_form_variant:
    path: /contact
    controller: App\Controller\Message\ContactPageController::writeMessageToDB
    methods:    [POST]

send_first_simple_form_variant:
    path: /send
    controller: App\Controller\Message\ContactPageController::sendMessageFromForm
    methods:    [POST]

api_get_all_messages:
    path: /api/get_all
    controller: App\Controller\Message\ClientAPIController::getAll
    methods:    [GET]

api_get_messages_by_email:
    path: /api/get_by_email/{email}
    controller: App\Controller\Message\ClientAPIController::getByEmail
    methods:    [GET]


api_post_one_by_id_message:
    path: /api/get_by_id/
    controller: App\Controller\Message\ClientAPIController::findOneMessageById
    methods:    [POST]


api_create_message:
    path: /api/write
    controller: App\Controller\Message\ClientAPIController::createOne
    methods:    [POST]
